### ISSUE TITLE
Add stylelint-order

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/stylelint-config-cloudfour#129]
Add [stylelint-order](https://github.com/hudochenkov/stylelint-order) to enforce both alphabetical property order and also to ensure `@extend` and `@include` statements are at the top of a block.

See discussion in https://github.com/cloudfour/cloudfour.com-patterns/pull/1077

**Comment by tylersticka** [comment]
Should we also disallow `@extend` since it's often considered [an anti-pattern](https://csswizardry.com/2016/02/mixins-better-for-performance/) these days?

**Comment by spaceninja** [comment]
Moved the @extend issue to #213 becuase it's trivially easy to handle
