### ISSUE TITLE
Enforce quote styles in Sass commands

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/stylelint-config-cloudfour#131]
@tylersticka [said](https://github.com/cloudfour/cloudfour.com-patterns/pull/1077#discussion_r539742408):

> I've also noticed our linting/formatting isn't enforcing quote styles in Sass commands like `@use`.

It's possible that #130 will fix this.

**Comment by spaceninja** [comment]
@tylersticka stylelint-scss will enforce double quotes on `@use` statements if you try to use single quotes, but it won't force quotes in the first place. My test showed that `@use sass:math;` and `@use "sass:math";` both passed lint.

Is this sufficient, or would you like me to keep looking for a way to enforce quotes?

**Comment by tylersticka** [comment]
Does `@use path` without quotes actually work? Weird.

I think that's fine. 🤷
