### ISSUE TITLE
Add Greenkeeper

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/stylelint-config-cloudfour#4]
Add Greenkeeper to automatically check for updates to NPM dependencies. Add greenkeeper badge.

**Comment by calebeby** [comment]
I've used both renovate and greenkeeper and renovate worked a lot better for me (opens update PR's more consistently and sooner after versions are released, has options for batching multiple updates into the same PR, better support for lockfile updates). It is free for open source, like Greenkeeper https://renovatebot.com/

**Comment by spaceninja** [comment]
Thanks for the suggestion! I switch to Renovate.
