### ISSUE TITLE
Ignore `transition` and `animation` from `declaration-block-no-redundant-longhand-properties` rule

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/stylelint-config-cloudfour#407]
It is especially helpful when adding CSS transitions or keyframe animations to use longhand properties.

We should be able to ignore `transition` and `animation` and I think that would be enough: https://stylelint.io/user-guide/rules/declaration-block-no-redundant-longhand-properties/#optional-secondary-options

**Comment by Paul-Hebert** [comment]
Thanks for filing this Gerardo! I agree.

To be honest I'd also be fine disabling this rule altogether for a few reasons:

- When using custom properties the shorthand can get really long
- Sometimes the short hands can get confusing for properties with lots of values (e.g. the font example in the "valid patterns" section of the docs)
- I honestly have to spend time thinking every time I see `margin: 1px 2px 3px 4px` to remember which value affects which side.

That might just be me though 🤷

**Comment by gerardo-rodriguez** [comment]
I'm totally cool disabling it all together. 👍🏽

**Comment by spaceninja** [comment]
Disabling it altogether is probably the best option if we're finding ourselves disabling it a lot. Linting is only helpful if it's, you know, helpful. ;)
